# Generated by Django 5.0.3 on 2024-04-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='about',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='responsibilities',
        ),
    ]
