# Generated by Django 5.0.3 on 2024-03-28 17:05

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='about',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='about',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
