# Generated by Django 5.0.3 on 2024-03-28 17:09

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_joblisting_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='benefits',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='responsibilities',
            field=django_summernote.fields.SummernoteTextField(blank=True, null=True),
        ),
    ]
