# Generated by Django 5.0.3 on 2024-04-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_about_joblisting_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='name',
        ),
    ]
