# Generated by Django 5.0.3 on 2024-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_personalinformation_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
