# Generated by Django 5.0.3 on 2024-03-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_joblisting_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default-profile.jpeg', null=True, upload_to='images/'),
        ),
    ]
