# Generated by Django 5.0.3 on 2024-03-12 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_month', models.CharField(max_length=10)),
                ('start_year', models.IntegerField()),
                ('end_month', models.CharField(blank=True, max_length=10, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False, blank=True)),
                ('task_one', models.CharField(max_length=255)),
                ('task_two', models.CharField(blank=True, max_length=255, null=True)),
                ('task_three', models.CharField(blank=True, max_length=255, null=True)),
                ('task_four', models.CharField(blank=True, max_length=255, null=True)),
                ('task_five', models.CharField(blank=True, max_length=255, null=True)),
                ('task_six', models.CharField(blank=True, max_length=255, null=True)),
                ('task_seven', models.CharField(blank=True, max_length=255, null=True)),
                ('task_eight', models.CharField(blank=True, max_length=255, null=True)),
                ('task_nine', models.CharField(blank=True, max_length=255, null=True)),
                ('task_ten', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
