# Generated by Django 5.0.3 on 2024-03-29 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_joblisting_created_at_savedjobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_id',
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.joblisting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedjobs',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
