# Generated by Django 5.0.3 on 2024-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_jobskill_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
