# Generated by Django 5.0.3 on 2024-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_experience_currently_working_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
