# Generated by Django 5.0.3 on 2024-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_personalinformation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(default='images/default-profile.jpeg', upload_to='images/'),
        ),
    ]
