# Generated by Django 5.0.3 on 2024-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_experience_end_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='task_one',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
