# Generated by Django 5.0.3 on 2024-04-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_education_user_id_remove_experience_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjobs',
            old_name='user_id',
            new_name='user',
        ),
    ]
