# Generated by Django 5.0.3 on 2024-04-13 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_user_id_savedjobs_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
        migrations.AddField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user_id',
        ),
    ]
