# Generated by Django 5.0.3 on 2024-03-21 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_experience_end_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('pay_bottom', models.IntegerField(blank=True, null=True)),
                ('pay_top', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('skill_one', models.CharField(max_length=255)),
                ('skill_two', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_three', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_four', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_five', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_six', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_seven', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_eight', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
