# Generated by Django 5.0.3 on 2024-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
