# Generated by Django 5.0.3 on 2024-04-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_userskill_unique_together_userskill_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobskill',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='skill_id',
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.joblisting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.skill'),
            preserve_default=False,
        ),
    ]
