# Generated by Django 5.0.3 on 2024-03-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_joblisting_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_eight',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_five',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_four',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_one',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_seven',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_six',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_three',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='skill_two',
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.BigIntegerField()),
                ('skill_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='website.joblisting')),
            ],
        ),
    ]
