# Generated by Django 5.0.3 on 2024-03-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_joblisting_skill_eight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskill',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='website.joblisting'),
        ),
    ]
